# Generated by Django 3.2.7 on 2021-09-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_is_superuser_account_is_superadmin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_superadmin",
            new_name="is_superuser",
        ),
    ]
